### ISSUE TITLE
Question about Formula 7 in the paper

### ISSUE THREAD

**Issue by flyinghippof** [kcheng1021/UC-NeRF#1]
Thank you to the author for releasing such an excellent article.
I have some questions about Announcement 7 in the article
![image](https://github.com/kcheng1021/UC-NeRF/assets/72117809/5858dbd8-cdf5-4f7b-884f-c8a0019e1c98)
Pixels do not have a definite depth, so the projection seems incorrect. 
Can I understand it as using the depth estimated by MVS here

**Comment by kcheng1021** [comment]
Thanks for your attention and question on our work!
Yes. Once the poses have metric, the definite depth could also be recovered. The poses refinement codes will release soon. Hope my answer helps you. Feel free to ask. I want response as soon as possible.

**Comment by flyinghippof** [comment]
Thanks for your reply！
What I want to say is：p and q are pixels in the images，They can be expressed as (u,v,1)，and real-world depth information is lost，when there is transformation in T, is it not possible to use this projection transformation?

**Comment by kcheng1021** [comment]
Sorry for reply late.  If the transformation T is metric, then the metric depth information can be recovered by triangulation or MVS.
