### ISSUE TITLE
Model released

### ISSUE THREAD

**Issue by VLadImirluren** [kcheng1021/UC-NeRF#2]
Thanks to your great work!

I am very concerned about whether you will released the nerf model trained on waymo or nuscene etc.?

best wishes~

非常棒的工作！

我非常关心您是否会公开在waymo或是nuscene等室外驾驶数据集上的重建nerf的模型？我非常想试试

祝好～

**Comment by kcheng1021** [comment]
Of course! The models are trained on DJI. So I am retraining them in school for public. I will realease the codes soon first, then release some pretrained models for inference.

**Comment by VLadImirluren** [comment]
> Of course! The models are trained on DJI. So I am retraining them in school for public. I will realease the codes soon first, then release some pretrained models for inference.

Thanks!!

非常感谢～
